//加载效果
window.onload=function(){
  sitewelcome.classList.remove("active")
}
//预览二维码
$(".preview1").hover(function(){
  $(".QRCode1").show();
},function(){$(".QRCode1").hide();})
$(".preview2").hover(function(){
  $(".QRCode2").show();
},function(){$(".QRCode2").hide();})